---
gunicorn_socket: /run/gunicorn/socket
gunicorn_socket_uri: "unix:{{ gunicorn_socket }}"

gunicorn_service_conf: /etc/systemd/system/gunicorn.service
gunicorn_socket_conf: /etc/systemd/system/gunicorn.socket
gunicorn_tempfile_conf: /etc/tmpfiles.d/gunicorn.conf
